# 2024/9/9
## This page is for converting the original dataset into 1-Dimension dataset with customized index
### The customized index is according header that is already defined

In [1]:
import numpy as np
import pandas as pd

# Setting up header

In [2]:
df = pd.read_excel('D:\\AI Warning\\3_CNN\\Data and Classification Model\\Classification\\header.xlsx')

In [3]:
coll = df.iloc[0,:]
roww = df.iloc[:,0]

In [4]:
print("Collumns are as follow: \n",coll)
print("\nRows are as follow: \n",roww)

Collumns are as follow:
 Unnamed: 0    NaN
Unnamed: 1    _S1
Unnamed: 2    _S2
Unnamed: 3    _S3
Unnamed: 4    _S4
Unnamed: 5    _S5
Unnamed: 6    _S6
Unnamed: 7    _S7
Unnamed: 8    _S8
Name: 0, dtype: object

Rows are as follow:
 0         NaN
1      IE101
2      IE109
3      IE110
4      IE114
        ...
109    IE629
110    IE630
111    IE631
112    IE632
113    IE999
Name: Unnamed: 0, Length: 114, dtype: object

In [5]:
roww = roww.dropna()

In [6]:
coll = coll.dropna()

In [7]:
print("Collumns are as follow: \n",coll)
print("\nRows are as follow: \n",roww)

Collumns are as follow:
 Unnamed: 1    _S1
Unnamed: 2    _S2
Unnamed: 3    _S3
Unnamed: 4    _S4
Unnamed: 5    _S5
Unnamed: 6    _S6
Unnamed: 7    _S7
Unnamed: 8    _S8
Name: 0, dtype: object

Rows are as follow:
 1      IE101
2      IE109
3      IE110
4      IE114
5      IE117
        ...
109    IE629
110    IE630
111    IE631
112    IE632
113    IE999
Name: Unnamed: 0, Length: 113, dtype: object

In [8]:
roww = roww.values
coll = coll.values

In [9]:
coll

array(['_S1', '_S2', '_S3', '_S4', '_S5', '_S6', '_S7', '_S8'],
      dtype=object)

In [10]:
all_list = [r + c for r in roww for c in coll]

In [11]:
new_items = ['Admission_line','Entrance year','Entrance grade','Graduation year','Graduation semester','Gender','Graduation status','Graduation grade']

In [12]:
all_list[0:0] = new_items

In [13]:
all_list

['Admission_line',
 'Entrance year',
 'Entrance grade',
 'Graduation year',
 'Graduation semester',
 'Gender',
 'Graduation status',
 'Graduation grade',
 'IE101 _S1',
 'IE101 _S2',
 'IE101 _S3',
 'IE101 _S4',
 'IE101 _S5',
 'IE101 _S6',
 'IE101 _S7',
 'IE101 _S8',
 'IE109 _S1',
 'IE109 _S2',
 'IE109 _S3',
 'IE109 _S4',
 'IE109 _S5',
 'IE109 _S6',
 'IE109 _S7',
 'IE109 _S8',
 'IE110 _S1',
 'IE110 _S2',
 'IE110 _S3',
 'IE110 _S4',
 'IE110 _S5',
 'IE110 _S6',
 'IE110 _S7',
 'IE110 _S8',
 'IE114 _S1',
 'IE114 _S2',
 'IE114 _S3',
 'IE114 _S4',
 'IE114 _S5',
 'IE114 _S6',
 'IE114 _S7',
 'IE114 _S8',
 'IE117 _S1',
 'IE117 _S2',
 'IE117 _S3',
 'IE117 _S4',
 'IE117 _S5',
 'IE117 _S6',
 'IE117 _S7',
 'IE117 _S8',
 'IE118 _S1',
 'IE118 _S2',
 'IE118 _S3',
 'IE118 _S4',
 'IE118 _S5',
 'IE118 _S6',
 'IE118 _S7',
 'IE118 _S8',
 'IE120 _S1',
 'IE120 _S2',
 'IE120 _S3',
 'IE120 _S4',
 'IE120 _S5',
 'IE120 _S6',
 'IE120 _S7',
 'IE120 _S8',
 'IE121 _S1',
 'IE121 _S2',
 'IE121 _S3',
 'IE121 _S4',
 'IE121 _S5',
 'IE121 _S6',
 'IE121 _S7',
 'IE121 _S8',
 'IE122 _S1',
 'IE122 _S2',
 'IE122 _S3',
 'IE122 _S4',
 'IE122 _S5',
 'IE122 _S6',
 'IE122 _S7',
 'IE122 _S8',
 'IE203 _S1',
 'IE203 _S2',
 'IE203 _S3',
 'IE203 _S4',
 'IE203 _S5',
 'IE203 _S6',
 'IE203 _S7',
 'IE203 _S8',
 'IE204 _S1',
 'IE204 _S2',
 'IE204 _S3',
 'IE204 _S4',
 'IE204 _S5',
 'IE204 _S6',
 'IE204 _S7',
 'IE204 _S8',
 'IE209 _S1',
 'IE209 _S2',
 'IE209 _S3',
 'IE209 _S4',
 'IE209 _S5',
 'IE209 _S6',
 'IE209 _S7',
 'IE209 _S8',
 'IE211 _S1',
 'IE211 _S2',
 'IE211 _S3',
 'IE211 _S4',
 'IE211 _S5',
 'IE211 _S6',
 'IE211 _S7',
 'IE211 _S8',
 'IE212 _S1',
 'IE212 _S2',
 'IE212 _S3',
 'IE212 _S4',
 'IE212 _S5',
 'IE212 _S6',
 'IE212 _S7',
 'IE212 _S8',
 'IE215 _S1',
 'IE215 _S2',
 'IE215 _S3',
 'IE215 _S4',
 'IE215 _S5',
 'IE215 _S6',
 'IE215 _S7',
 'IE215 _S8',
 'IE217 _S1',
 'IE217 _S2',
 'IE217 _S3',
 'IE217 _S4',
 'IE217 _S5',
 'IE217 _S6',
 'IE217 _S7',
 'IE217 _S8',
 'IE220 _S1',
 'IE220 _S2',
 'IE220 _S3',
 'IE220 _S4',
 'IE220 _S5',
 'IE220 _S6',
 'IE220 _S7',
 'IE220 _S8',
 'IE222 _S1',
 'IE222 _S2',
 'IE222 _S3',
 'IE222 _S4',
 'IE222 _S5',
 'IE222 _S6',
 'IE222 _S7',
 'IE222 _S8',
 'IE226 _S1',
 'IE226 _S2',
 'IE226 _S3',
 'IE226 _S4',
 'IE226 _S5',
 'IE226 _S6',
 'IE226 _S7',
 'IE226 _S8',
 'IE230 _S1',
 'IE230 _S2',
 'IE230 _S3',
 'IE230 _S4',
 'IE230 _S5',
 'IE230 _S6',
 'IE230 _S7',
 'IE230 _S8',
 'IE231 _S1',
 'IE231 _S2',
 'IE231 _S3',
 'IE231 _S4',
 'IE231 _S5',
 'IE231 _S6',
 'IE231 _S7',
 'IE231 _S8',
 'IE232 _S1',
 'IE232 _S2',
 'IE232 _S3',
 'IE232 _S4',
 'IE232 _S5',
 'IE232 _S6',
 'IE232 _S7',
 'IE232 _S8',
 'IE233 _S1',
 'IE233 _S2',
 'IE233 _S3',
 'IE233 _S4',
 'IE233 _S5',
 'IE233 _S6',
 'IE233 _S7',
 'IE233 _S8',
 'IE235 _S1',
 'IE235 _S2',
 'IE235 _S3',
 'IE235 _S4',
 'IE235 _S5',
 'IE235 _S6',
 'IE235 _S7',
 'IE235 _S8',
 'IE236 _S1',
 'IE236 _S2',
 'IE236 _S3',
 'IE236 _S4',
 'IE236 _S5',
 'IE236 _S6',
 'IE236 _S7',
 'IE236 _S8',
 'IE237 _S1',
 'IE237 _S2',
 'IE237 _S3',
 'IE237 _S4',
 'IE237 _S5',
 'IE237 _S6',
 'IE237 _S7',
 'IE237 _S8',
 'IE243 _S1',
 'IE243 _S2',
 'IE243 _S3',
 'IE243 _S4',
 'IE243 _S5',
 'IE243 _S6',
 'IE243 _S7',
 'IE243 _S8',
 'IE244 _S1',
 'IE244 _S2',
 'IE244 _S3',
 'IE244 _S4',
 'IE244 _S5',
 'IE244 _S6',
 'IE244 _S7',
 'IE244 _S8',
 'IE245 _S1',
 'IE245 _S2',
 'IE245 _S3',
 'IE245 _S4',
 'IE245 _S5',
 'IE245 _S6',
 'IE245 _S7',
 'IE245 _S8',
 'IE247 _S1',
 'IE247 _S2',
 'IE247 _S3',
 'IE247 _S4',
 'IE247 _S5',
 'IE247 _S6',
 'IE247 _S7',
 'IE247 _S8',
 'IE301 _S1',
 'IE301 _S2',
 'IE301 _S3',
 'IE301 _S4',
 'IE301 _S5',
 'IE301 _S6',
 'IE301 _S7',
 'IE301 _S8',
 'IE302 _S1',
 'IE302 _S2',
 'IE302 _S3',
 'IE302 _S4',
 'IE302 _S5',
 'IE302 _S6',
 'IE302 _S7',
 'IE302 _S8',
 'IE303 _S1',
 'IE303 _S2',
 'IE303 _S3',
 'IE303 _S4',
 'IE303 _S5',
 'IE303 _S6',
 'IE303 _S7',
 'IE303 _S8',
 'IE304 _S1',
 'IE304 _S2',
 'IE304 _S3',
 'IE304 _S4',
 'IE304 _S5',
 'IE304 _S6',
 'IE304 _S7',
 'IE304 _S8',
 'IE308 _S1',
 'IE308 _S2',
 'IE308 _S3',
 'IE308 _S4',
 'IE308 _S5',
 'IE308 _S6',
 'IE308 _S7',
 'IE308 _S8',
 'IE312 _S1',
 'IE312 _S2',
 'IE312 _S3',
 'IE312 _S4',
 'IE312 _S5',
 'IE312 _S6',
 'IE312 _S7',
 'IE312 _S8',
 'IE313 _S1',
 'IE313 _S2',
 'IE313 _S3',
 'IE313 _S4',
 'IE313 _S5',
 'IE313 _S6',
 'IE313 _S7',
 'IE313 _S8',
 'IE322 _S1',
 'IE322 _S2',
 'IE322 _S3',
 'IE322 _S4',
 'IE322 _S5',
 'IE322 _S6',
 'IE322 _S7',
 'IE322 _S8',
 'IE326 _S1',
 'IE326 _S2',
 'IE326 _S3',
 'IE326 _S4',
 'IE326 _S5',
 'IE326 _S6',
 'IE326 _S7',
 'IE326 _S8',
 'IE329 _S1',
 'IE329 _S2',
 'IE329 _S3',
 'IE329 _S4',
 'IE329 _S5',
 'IE329 _S6',
 'IE329 _S7',
 'IE329 _S8',
 'IE335 _S1',
 'IE335 _S2',
 'IE335 _S3',
 'IE335 _S4',
 'IE335 _S5',
 'IE335 _S6',
 'IE335 _S7',
 'IE335 _S8',
 'IE337 _S1',
 'IE337 _S2',
 'IE337 _S3',
 'IE337 _S4',
 'IE337 _S5',
 'IE337 _S6',
 'IE337 _S7',
 'IE337 _S8',
 'IE342 _S1',
 'IE342 _S2',
 'IE342 _S3',
 'IE342 _S4',
 'IE342 _S5',
 'IE342 _S6',
 'IE342 _S7',
 'IE342 _S8',
 'IE346 _S1',
 'IE346 _S2',
 'IE346 _S3',
 'IE346 _S4',
 'IE346 _S5',
 'IE346 _S6',
 'IE346 _S7',
 'IE346 _S8',
 'IE347 _S1',
 'IE347 _S2',
 'IE347 _S3',
 'IE347 _S4',
 'IE347 _S5',
 'IE347 _S6',
 'IE347 _S7',
 'IE347 _S8',
 'IE348 _S1',
 'IE348 _S2',
 'IE348 _S3',
 'IE348 _S4',
 'IE348 _S5',
 'IE348 _S6',
 'IE348 _S7',
 'IE348 _S8',
 'IE349 _S1',
 'IE349 _S2',
 'IE349 _S3',
 'IE349 _S4',
 'IE349 _S5',
 'IE349 _S6',
 'IE349 _S7',
 'IE349 _S8',
 'IE350 _S1',
 'IE350 _S2',
 'IE350 _S3',
 'IE350 _S4',
 'IE350 _S5',
 'IE350 _S6',
 'IE350 _S7',
 'IE350 _S8',
 'IE351 _S1',
 'IE351 _S2',
 'IE351 _S3',
 'IE351 _S4',
 'IE351 _S5',
 'IE351 _S6',
 'IE351 _S7',
 'IE351 _S8',
 'IE352 _S1',
 'IE352 _S2',
 'IE352 _S3',
 'IE352 _S4',
 'IE352 _S5',
 'IE352 _S6',
 'IE352 _S7',
 'IE352 _S8',
 'IE354 _S1',
 'IE354 _S2',
 'IE354 _S3',
 'IE354 _S4',
 'IE354 _S5',
 'IE354 _S6',
 'IE354 _S7',
 'IE354 _S8',
 'IE356 _S1',
 'IE356 _S2',
 'IE356 _S3',
 'IE356 _S4',
 'IE356 _S5',
 'IE356 _S6',
 'IE356 _S7',
 'IE356 _S8',
 'IE369 _S1',
 'IE369 _S2',
 'IE369 _S3',
 'IE369 _S4',
 'IE369 _S5',
 'IE369 _S6',
 'IE369 _S7',
 'IE369 _S8',
 'IE371 _S1',
 'IE371 _S2',
 'IE371 _S3',
 'IE371 _S4',
 'IE371 _S5',
 'IE371 _S6',
 'IE371 _S7',
 'IE371 _S8',
 'IE375 _S1',
 'IE375 _S2',
 'IE375 _S3',
 'IE375 _S4',
 'IE375 _S5',
 'IE375 _S6',
 'IE375 _S7',
 'IE375 _S8',
 'IE376 _S1',
 'IE376 _S2',
 'IE376 _S3',
 'IE376 _S4',
 'IE376 _S5',
 'IE376 _S6',
 'IE376 _S7',
 'IE376 _S8',
 'IE392 _S1',
 'IE392 _S2',
 'IE392 _S3',
 'IE392 _S4',
 'IE392 _S5',
 'IE392 _S6',
 'IE392 _S7',
 'IE392 _S8',
 'IE406 _S1',
 'IE406 _S2',
 'IE406 _S3',
 'IE406 _S4',
 'IE406 _S5',
 'IE406 _S6',
 'IE406 _S7',
 'IE406 _S8',
 'IE407 _S1',
 'IE407 _S2',
 'IE407 _S3',
 'IE407 _S4',
 'IE407 _S5',
 'IE407 _S6',
 'IE407 _S7',
 'IE407 _S8',
 'IE410 _S1',
 'IE410 _S2',
 'IE410 _S3',
 'IE410 _S4',
 'IE410 _S5',
 'IE410 _S6',
 'IE410 _S7',
 'IE410 _S8',
 'IE423 _S1',
 'IE423 _S2',
 'IE423 _S3',
 'IE423 _S4',
 'IE423 _S5',
 'IE423 _S6',
 'IE423 _S7',
 'IE423 _S8',
 'IE426 _S1',
 'IE426 _S2',
 'IE426 _S3',
 'IE426 _S4',
 'IE426 _S5',
 'IE426 _S6',
 'IE426 _S7',
 'IE426 _S8',
 'IE427 _S1',
 'IE427 _S2',
 'IE427 _S3',
 'IE427 _S4',
 'IE427 _S5',
 'IE427 _S6',
 'IE427 _S7',
 'IE427 _S8',
 'IE428 _S1',
 'IE428 _S2',
 'IE428 _S3',
 'IE428 _S4',
 'IE428 _S5',
 'IE428 _S6',
 'IE428 _S7',
 'IE428 _S8',
 'IE431 _S1',
 'IE431 _S2',
 'IE431 _S3',
 'IE431 _S4',
 'IE431 _S5',
 'IE431 _S6',
 'IE431 _S7',
 'IE431 _S8',
 'IE435 _S1',
 'IE435 _S2',
 'IE435 _S3',
 'IE435 _S4',
 'IE435 _S5',
 'IE435 _S6',
 'IE435 _S7',
 'IE435 _S8',
 'IE438 _S1',
 'IE438 _S2',
 'IE438 _S3',
 'IE438 _S4',
 'IE438 _S5',
 'IE438 _S6',
 'IE438 _S7',
 'IE438 _S8',
 'IE440 _S1',
 'IE440 _S2',
 'IE440 _S3',
 'IE440 _S4',
 'IE440 _S5',
 'IE440 _S6',
 'IE440 _S7',
 'IE440 _S8',
 'IE503 _S1',
 'IE503 _S2',
 'IE503 _S3',
 'IE503 _S4',
 'IE503 _S5',
 'IE503 _S6',
 'IE503 _S7',
 'IE503 _S8',
 'IE507 _S1',
 'IE507 _S2',
 'IE507 _S3',
 'IE507 _S4',
 'IE507 _S5',
 'IE507 _S6',
 'IE507 _S7',
 'IE507 _S8',
 'IE508 _S1',
 'IE508 _S2',
 'IE508 _S3',
 'IE508 _S4',
 'IE508 _S5',
 'IE508 _S6',
 'IE508 _S7',
 'IE508 _S8',
 'IE517 _S1',
 'IE517 _S2',
 'IE517 _S3',
 'IE517 _S4',
 'IE517 _S5',
 'IE517 _S6',
 'IE517 _S7',
 'IE517 _S8',
 'IE518 _S1',
 'IE518 _S2',
 'IE518 _S3',
 'IE518 _S4',
 'IE518 _S5',
 'IE518 _S6',
 'IE518 _S7',
 'IE518 _S8',
 'IE531 _S1',
 'IE531 _S2',
 'IE531 _S3',
 'IE531 _S4',
 'IE531 _S5',
 'IE531 _S6',
 'IE531 _S7',
 'IE531 _S8',
 'IE533 _S1',
 'IE533 _S2',
 'IE533 _S3',
 'IE533 _S4',
 'IE533 _S5',
 'IE533 _S6',
 'IE533 _S7',
 'IE533 _S8',
 'IE534 _S1',
 'IE534 _S2',
 'IE534 _S3',
 'IE534 _S4',
 'IE534 _S5',
 'IE534 _S6',
 'IE534 _S7',
 'IE534 _S8',
 'IE537 _S1',
 'IE537 _S2',
 'IE537 _S3',
 'IE537 _S4',
 'IE537 _S5',
 'IE537 _S6',
 'IE537 _S7',
 'IE537 _S8',
 'IE538 _S1',
 'IE538 _S2',
 'IE538 _S3',
 'IE538 _S4',
 'IE538 _S5',
 'IE538 _S6',
 'IE538 _S7',
 'IE538 _S8',
 'IE541 _S1',
 'IE541 _S2',
 'IE541 _S3',
 'IE541 _S4',
 'IE541 _S5',
 'IE541 _S6',
 'IE541 _S7',
 'IE541 _S8',
 'IE543 _S1',
 'IE543 _S2',
 'IE543 _S3',
 'IE543 _S4',
 'IE543 _S5',
 'IE543 _S6',
 'IE543 _S7',
 'IE543 _S8',
 'IE562 _S1',
 'IE562 _S2',
 'IE562 _S3',
 'IE562 _S4',
 'IE562 _S5',
 'IE562 _S6',
 'IE562 _S7',
 'IE562 _S8',
 'IE571 _S1',
 'IE571 _S2',
 'IE571 _S3',
 'IE571 _S4',
 'IE571 _S5',
 'IE571 _S6',
 'IE571 _S7',
 'IE571 _S8',
 'IE574 _S1',
 'IE574 _S2',
 'IE574 _S3',
 'IE574 _S4',
 'IE574 _S5',
 'IE574 _S6',
 'IE574 _S7',
 'IE574 _S8',
 'IE579 _S1',
 'IE579 _S2',
 'IE579 _S3',
 'IE579 _S4',
 'IE579 _S5',
 'IE579 _S6',
 'IE579 _S7',
 'IE579 _S8',
 'IE581 _S1',
 'IE581 _S2',
 'IE581 _S3',
 'IE581 _S4',
 'IE581 _S5',
 'IE581 _S6',
 'IE581 _S7',
 'IE581 _S8',
 'IE586 _S1',
 'IE586 _S2',
 'IE586 _S3',
 'IE586 _S4',
 'IE586 _S5',
 'IE586 _S6',
 'IE586 _S7',
 'IE586 _S8',
 'IE590 _S1',
 'IE590 _S2',
 'IE590 _S3',
 'IE590 _S4',
 'IE590 _S5',
 'IE590 _S6',
 'IE590 _S7',
 'IE590 _S8',
 'IE591 _S1',
 'IE591 _S2',
 'IE591 _S3',
 'IE591 _S4',
 'IE591 _S5',
 'IE591 _S6',
 'IE591 _S7',
 'IE591 _S8',
 'IE592 _S1',
 'IE592 _S2',
 'IE592 _S3',
 'IE592 _S4',
 'IE592 _S5',
 'IE592 _S6',
 'IE592 _S7',
 'IE592 _S8',
 'IE599 _S1',
 'IE599 _S2',
 'IE599 _S3',
 'IE599 _S4',
 'IE599 _S5',
 'IE599 _S6',
 'IE599 _S7',
 'IE599 _S8',
 'IE600 _S1',
 'IE600 _S2',
 'IE600 _S3',
 'IE600 _S4',
 'IE600 _S5',
 'IE600 _S6',
 'IE600 _S7',
 'IE600 _S8',
 'IE602 _S1',
 'IE602 _S2',
 'IE602 _S3',
 'IE602 _S4',
 'IE602 _S5',
 'IE602 _S6',
 'IE602 _S7',
 'IE602 _S8',
 'IE605 _S1',
 'IE605 _S2',
 'IE605 _S3',
 'IE605 _S4',
 'IE605 _S5',
 'IE605 _S6',
 'IE605 _S7',
 'IE605 _S8',
 'IE607 _S1',
 'IE607 _S2',
 'IE607 _S3',
 'IE607 _S4',
 'IE607 _S5',
 'IE607 _S6',
 'IE607 _S7',
 'IE607 _S8',
 'IE609 _S1',
 'IE609 _S2',
 'IE609 _S3',
 'IE609 _S4',
 'IE609 _S5',
 'IE609 _S6',
 'IE609 _S7',
 'IE609 _S8',
 'IE610 _S1',
 'IE610 _S2',
 'IE610 _S3',
 'IE610 _S4',
 'IE610 _S5',
 'IE610 _S6',
 'IE610 _S7',
 'IE610 _S8',
 'IE613 _S1',
 'IE613 _S2',
 'IE613 _S3',
 'IE613 _S4',
 'IE613 _S5',
 'IE613 _S6',
 'IE613 _S7',
 'IE613 _S8',
 'IE614 _S1',
 'IE614 _S2',
 'IE614 _S3',
 'IE614 _S4',
 'IE614 _S5',
 'IE614 _S6',
 'IE614 _S7',
 'IE614 _S8',
 'IE615 _S1',
 'IE615 _S2',
 'IE615 _S3',
 'IE615 _S4',
 'IE615 _S5',
 'IE615 _S6',
 'IE615 _S7',
 'IE615 _S8',
 'IE618 _S1',
 'IE618 _S2',
 'IE618 _S3',
 'IE618 _S4',
 'IE618 _S5',
 'IE618 _S6',
 'IE618 _S7',
 'IE618 _S8',
 'IE619 _S1',
 'IE619 _S2',
 'IE619 _S3',
 'IE619 _S4',
 'IE619 _S5',
 'IE619 _S6',
 'IE619 _S7',
 'IE619 _S8',
 'IE622 _S1',
 'IE622 _S2',
 'IE622 _S3',
 'IE622 _S4',
 'IE622 _S5',
 'IE622 _S6',
 'IE622 _S7',
 'IE622 _S8',
 'IE623 _S1',
 'IE623 _S2',
 'IE623 _S3',
 'IE623 _S4',
 'IE623 _S5',
 'IE623 _S6',
 'IE623 _S7',
 'IE623 _S8',
 'IE624 _S1',
 'IE624 _S2',
 'IE624 _S3',
 'IE624 _S4',
 'IE624 _S5',
 'IE624 _S6',
 'IE624 _S7',
 'IE624 _S8',
 'IE625 _S1',
 'IE625 _S2',
 'IE625 _S3',
 'IE625 _S4',
 'IE625 _S5',
 'IE625 _S6',
 'IE625 _S7',
 'IE625 _S8',
 'IE626 _S1',
 'IE626 _S2',
 'IE626 _S3',
 'IE626 _S4',
 'IE626 _S5',
 'IE626 _S6',
 'IE626 _S7',
 'IE626 _S8',
 'IE627 _S1',
 'IE627 _S2',
 'IE627 _S3',
 'IE627 _S4',
 'IE627 _S5',
 'IE627 _S6',
 'IE627 _S7',
 'IE627 _S8',
 'IE628 _S1',
 'IE628 _S2',
 'IE628 _S3',
 'IE628 _S4',
 'IE628 _S5',
 'IE628 _S6',
 'IE628 _S7',
 'IE628 _S8',
 'IE629 _S1',
 'IE629 _S2',
 'IE629 _S3',
 'IE629 _S4',
 'IE629 _S5',
 'IE629 _S6',
 'IE629 _S7',
 'IE629 _S8',
 'IE630 _S1',
 'IE630 _S2',
 'IE630 _S3',
 'IE630 _S4',
 'IE630 _S5',
 'IE630 _S6',
 'IE630 _S7',
 'IE630 _S8',
 'IE631 _S1',
 'IE631 _S2',
 'IE631 _S3',
 'IE631 _S4',
 'IE631 _S5',
 'IE631 _S6',
 'IE631 _S7',
 'IE631 _S8',
 'IE632 _S1',
 'IE632 _S2',
 'IE632 _S3',
 'IE632 _S4',
 'IE632 _S5',
 'IE632 _S6',
 'IE632 _S7',
 'IE632 _S8',
 'IE999 _S1',
 'IE999 _S2',
 'IE999 _S3',
 'IE999 _S4',
 'IE999 _S5',
 'IE999 _S6',
 'IE999 _S7',
 'IE999 _S8']

# Tranforming the Raw Data

In [14]:
df1 = pd.read_excel('D:\\AI Warning\\3_CNN\\Data and Classification Model\\Matching 108\\102-108\\classification_combined.xlsx', sheet_name="S8")

In [15]:
# Extract features into numpy array X

df1 = df1.drop(columns = ['課名','班別','PR','先修_1','先修_2','暑修_1','暑修_2'])
X = df1.iloc[1:, 1:-1].values

# Extract target variable into numpy array y
y = df1.iloc[1:735, -1] 
y = y.dropna()

print(X.shape)
print(y.shape)

(83676, 8)
(734,)

In [16]:
X

array([[3, 0, 0, ..., 2, 0, 0],
       [69, 0, 0, ..., 0, 0, 0],
       [64, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 86],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 90]], dtype=object)

In [17]:
y

1      0
2      0
3      1
4      1
5      0
      ..
730    0
731    0
732    0
733    0
734    0
Name: Unnamed: 16, Length: 734, dtype: object

In [18]:
X = X.reshape(-1, 114, 8, 1) 
X = pd.DataFrame(X.reshape(734, -1))
X

,0,1,2,3,4,5,6,7,8,9,...,902,903,904,905,906,907,908,909,910,911
0,3,0,0,0,0,2,0,0,69,0,...,0,0,0,0,0,0,0,0,0,0
1,4,0,0,0,0,2,0,0,90,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0,0,0,0,1,0,0,75,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,0,0,1,0,0,74,0,...,0,0,0,0,0,0,0,0,0,0
4,5,0,0,0,0,2,0,0,60,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,3,0,0,0,0,2,0,0,69,0,...,0,0,0,0,0,0,0,0,0,0
730,3,0,0,0,0,2,0,0,82,0,...,0,91,0,0,0,0,0,0,0,0
731,3,0,0,0,0,2,0,0,61,0,...,0,0,0,0,0,0,0,0,0,0
732,3,0,0,0,0,2,0,0,45,0,...,0,0,0,0,0,0,0,0,0,0
733,4,0,0,0,0,2,0,0,76,0,...,0,0,0,0,0,0,0,0,0,90

In [19]:
all_list

['Admission_line',
 'Entrance year',
 'Entrance grade',
 'Graduation year',
 'Graduation semester',
 'Gender',
 'Graduation status',
 'Graduation grade',
 'IE101 _S1',
 'IE101 _S2',
 'IE101 _S3',
 'IE101 _S4',
 'IE101 _S5',
 'IE101 _S6',
 'IE101 _S7',
 'IE101 _S8',
 'IE109 _S1',
 'IE109 _S2',
 'IE109 _S3',
 'IE109 _S4',
 'IE109 _S5',
 'IE109 _S6',
 'IE109 _S7',
 'IE109 _S8',
 'IE110 _S1',
 'IE110 _S2',
 'IE110 _S3',
 'IE110 _S4',
 'IE110 _S5',
 'IE110 _S6',
 'IE110 _S7',
 'IE110 _S8',
 'IE114 _S1',
 'IE114 _S2',
 'IE114 _S3',
 'IE114 _S4',
 'IE114 _S5',
 'IE114 _S6',
 'IE114 _S7',
 'IE114 _S8',
 'IE117 _S1',
 'IE117 _S2',
 'IE117 _S3',
 'IE117 _S4',
 'IE117 _S5',
 'IE117 _S6',
 'IE117 _S7',
 'IE117 _S8',
 'IE118 _S1',
 'IE118 _S2',
 'IE118 _S3',
 'IE118 _S4',
 'IE118 _S5',
 'IE118 _S6',
 'IE118 _S7',
 'IE118 _S8',
 'IE120 _S1',
 'IE120 _S2',
 'IE120 _S3',
 'IE120 _S4',
 'IE120 _S5',
 'IE120 _S6',
 'IE120 _S7',
 'IE120 _S8',
 'IE121 _S1',
 'IE121 _S2',
 'IE121 _S3',
 'IE121 _S4',
 'IE121 _S5',
 'IE121 _S6',
 'IE121 _S7',
 'IE121 _S8',
 'IE122 _S1',
 'IE122 _S2',
 'IE122 _S3',
 'IE122 _S4',
 'IE122 _S5',
 'IE122 _S6',
 'IE122 _S7',
 'IE122 _S8',
 'IE203 _S1',
 'IE203 _S2',
 'IE203 _S3',
 'IE203 _S4',
 'IE203 _S5',
 'IE203 _S6',
 'IE203 _S7',
 'IE203 _S8',
 'IE204 _S1',
 'IE204 _S2',
 'IE204 _S3',
 'IE204 _S4',
 'IE204 _S5',
 'IE204 _S6',
 'IE204 _S7',
 'IE204 _S8',
 'IE209 _S1',
 'IE209 _S2',
 'IE209 _S3',
 'IE209 _S4',
 'IE209 _S5',
 'IE209 _S6',
 'IE209 _S7',
 'IE209 _S8',
 'IE211 _S1',
 'IE211 _S2',
 'IE211 _S3',
 'IE211 _S4',
 'IE211 _S5',
 'IE211 _S6',
 'IE211 _S7',
 'IE211 _S8',
 'IE212 _S1',
 'IE212 _S2',
 'IE212 _S3',
 'IE212 _S4',
 'IE212 _S5',
 'IE212 _S6',
 'IE212 _S7',
 'IE212 _S8',
 'IE215 _S1',
 'IE215 _S2',
 'IE215 _S3',
 'IE215 _S4',
 'IE215 _S5',
 'IE215 _S6',
 'IE215 _S7',
 'IE215 _S8',
 'IE217 _S1',
 'IE217 _S2',
 'IE217 _S3',
 'IE217 _S4',
 'IE217 _S5',
 'IE217 _S6',
 'IE217 _S7',
 'IE217 _S8',
 'IE220 _S1',
 'IE220 _S2',
 'IE220 _S3',
 'IE220 _S4',
 'IE220 _S5',
 'IE220 _S6',
 'IE220 _S7',
 'IE220 _S8',
 'IE222 _S1',
 'IE222 _S2',
 'IE222 _S3',
 'IE222 _S4',
 'IE222 _S5',
 'IE222 _S6',
 'IE222 _S7',
 'IE222 _S8',
 'IE226 _S1',
 'IE226 _S2',
 'IE226 _S3',
 'IE226 _S4',
 'IE226 _S5',
 'IE226 _S6',
 'IE226 _S7',
 'IE226 _S8',
 'IE230 _S1',
 'IE230 _S2',
 'IE230 _S3',
 'IE230 _S4',
 'IE230 _S5',
 'IE230 _S6',
 'IE230 _S7',
 'IE230 _S8',
 'IE231 _S1',
 'IE231 _S2',
 'IE231 _S3',
 'IE231 _S4',
 'IE231 _S5',
 'IE231 _S6',
 'IE231 _S7',
 'IE231 _S8',
 'IE232 _S1',
 'IE232 _S2',
 'IE232 _S3',
 'IE232 _S4',
 'IE232 _S5',
 'IE232 _S6',
 'IE232 _S7',
 'IE232 _S8',
 'IE233 _S1',
 'IE233 _S2',
 'IE233 _S3',
 'IE233 _S4',
 'IE233 _S5',
 'IE233 _S6',
 'IE233 _S7',
 'IE233 _S8',
 'IE235 _S1',
 'IE235 _S2',
 'IE235 _S3',
 'IE235 _S4',
 'IE235 _S5',
 'IE235 _S6',
 'IE235 _S7',
 'IE235 _S8',
 'IE236 _S1',
 'IE236 _S2',
 'IE236 _S3',
 'IE236 _S4',
 'IE236 _S5',
 'IE236 _S6',
 'IE236 _S7',
 'IE236 _S8',
 'IE237 _S1',
 'IE237 _S2',
 'IE237 _S3',
 'IE237 _S4',
 'IE237 _S5',
 'IE237 _S6',
 'IE237 _S7',
 'IE237 _S8',
 'IE243 _S1',
 'IE243 _S2',
 'IE243 _S3',
 'IE243 _S4',
 'IE243 _S5',
 'IE243 _S6',
 'IE243 _S7',
 'IE243 _S8',
 'IE244 _S1',
 'IE244 _S2',
 'IE244 _S3',
 'IE244 _S4',
 'IE244 _S5',
 'IE244 _S6',
 'IE244 _S7',
 'IE244 _S8',
 'IE245 _S1',
 'IE245 _S2',
 'IE245 _S3',
 'IE245 _S4',
 'IE245 _S5',
 'IE245 _S6',
 'IE245 _S7',
 'IE245 _S8',
 'IE247 _S1',
 'IE247 _S2',
 'IE247 _S3',
 'IE247 _S4',
 'IE247 _S5',
 'IE247 _S6',
 'IE247 _S7',
 'IE247 _S8',
 'IE301 _S1',
 'IE301 _S2',
 'IE301 _S3',
 'IE301 _S4',
 'IE301 _S5',
 'IE301 _S6',
 'IE301 _S7',
 'IE301 _S8',
 'IE302 _S1',
 'IE302 _S2',
 'IE302 _S3',
 'IE302 _S4',
 'IE302 _S5',
 'IE302 _S6',
 'IE302 _S7',
 'IE302 _S8',
 'IE303 _S1',
 'IE303 _S2',
 'IE303 _S3',
 'IE303 _S4',
 'IE303 _S5',
 'IE303 _S6',
 'IE303 _S7',
 'IE303 _S8',
 'IE304 _S1',
 'IE304 _S2',
 'IE304 _S3',
 'IE304 _S4',
 'IE304 _S5',
 'IE304 _S6',
 'IE304 _S7',
 'IE304 _S8',
 'IE308 _S1',
 'IE308 _S2',
 'IE308 _S3',
 'IE308 _S4',
 'IE308 _S5',
 'IE308 _S6',
 'IE308 _S7',
 'IE308 _S8',
 'IE312 _S1',
 'IE312 _S2',
 'IE312 _S3',
 'IE312 _S4',
 'IE312 _S5',
 'IE312 _S6',
 'IE312 _S7',
 'IE312 _S8',
 'IE313 _S1',
 'IE313 _S2',
 'IE313 _S3',
 'IE313 _S4',
 'IE313 _S5',
 'IE313 _S6',
 'IE313 _S7',
 'IE313 _S8',
 'IE322 _S1',
 'IE322 _S2',
 'IE322 _S3',
 'IE322 _S4',
 'IE322 _S5',
 'IE322 _S6',
 'IE322 _S7',
 'IE322 _S8',
 'IE326 _S1',
 'IE326 _S2',
 'IE326 _S3',
 'IE326 _S4',
 'IE326 _S5',
 'IE326 _S6',
 'IE326 _S7',
 'IE326 _S8',
 'IE329 _S1',
 'IE329 _S2',
 'IE329 _S3',
 'IE329 _S4',
 'IE329 _S5',
 'IE329 _S6',
 'IE329 _S7',
 'IE329 _S8',
 'IE335 _S1',
 'IE335 _S2',
 'IE335 _S3',
 'IE335 _S4',
 'IE335 _S5',
 'IE335 _S6',
 'IE335 _S7',
 'IE335 _S8',
 'IE337 _S1',
 'IE337 _S2',
 'IE337 _S3',
 'IE337 _S4',
 'IE337 _S5',
 'IE337 _S6',
 'IE337 _S7',
 'IE337 _S8',
 'IE342 _S1',
 'IE342 _S2',
 'IE342 _S3',
 'IE342 _S4',
 'IE342 _S5',
 'IE342 _S6',
 'IE342 _S7',
 'IE342 _S8',
 'IE346 _S1',
 'IE346 _S2',
 'IE346 _S3',
 'IE346 _S4',
 'IE346 _S5',
 'IE346 _S6',
 'IE346 _S7',
 'IE346 _S8',
 'IE347 _S1',
 'IE347 _S2',
 'IE347 _S3',
 'IE347 _S4',
 'IE347 _S5',
 'IE347 _S6',
 'IE347 _S7',
 'IE347 _S8',
 'IE348 _S1',
 'IE348 _S2',
 'IE348 _S3',
 'IE348 _S4',
 'IE348 _S5',
 'IE348 _S6',
 'IE348 _S7',
 'IE348 _S8',
 'IE349 _S1',
 'IE349 _S2',
 'IE349 _S3',
 'IE349 _S4',
 'IE349 _S5',
 'IE349 _S6',
 'IE349 _S7',
 'IE349 _S8',
 'IE350 _S1',
 'IE350 _S2',
 'IE350 _S3',
 'IE350 _S4',
 'IE350 _S5',
 'IE350 _S6',
 'IE350 _S7',
 'IE350 _S8',
 'IE351 _S1',
 'IE351 _S2',
 'IE351 _S3',
 'IE351 _S4',
 'IE351 _S5',
 'IE351 _S6',
 'IE351 _S7',
 'IE351 _S8',
 'IE352 _S1',
 'IE352 _S2',
 'IE352 _S3',
 'IE352 _S4',
 'IE352 _S5',
 'IE352 _S6',
 'IE352 _S7',
 'IE352 _S8',
 'IE354 _S1',
 'IE354 _S2',
 'IE354 _S3',
 'IE354 _S4',
 'IE354 _S5',
 'IE354 _S6',
 'IE354 _S7',
 'IE354 _S8',
 'IE356 _S1',
 'IE356 _S2',
 'IE356 _S3',
 'IE356 _S4',
 'IE356 _S5',
 'IE356 _S6',
 'IE356 _S7',
 'IE356 _S8',
 'IE369 _S1',
 'IE369 _S2',
 'IE369 _S3',
 'IE369 _S4',
 'IE369 _S5',
 'IE369 _S6',
 'IE369 _S7',
 'IE369 _S8',
 'IE371 _S1',
 'IE371 _S2',
 'IE371 _S3',
 'IE371 _S4',
 'IE371 _S5',
 'IE371 _S6',
 'IE371 _S7',
 'IE371 _S8',
 'IE375 _S1',
 'IE375 _S2',
 'IE375 _S3',
 'IE375 _S4',
 'IE375 _S5',
 'IE375 _S6',
 'IE375 _S7',
 'IE375 _S8',
 'IE376 _S1',
 'IE376 _S2',
 'IE376 _S3',
 'IE376 _S4',
 'IE376 _S5',
 'IE376 _S6',
 'IE376 _S7',
 'IE376 _S8',
 'IE392 _S1',
 'IE392 _S2',
 'IE392 _S3',
 'IE392 _S4',
 'IE392 _S5',
 'IE392 _S6',
 'IE392 _S7',
 'IE392 _S8',
 'IE406 _S1',
 'IE406 _S2',
 'IE406 _S3',
 'IE406 _S4',
 'IE406 _S5',
 'IE406 _S6',
 'IE406 _S7',
 'IE406 _S8',
 'IE407 _S1',
 'IE407 _S2',
 'IE407 _S3',
 'IE407 _S4',
 'IE407 _S5',
 'IE407 _S6',
 'IE407 _S7',
 'IE407 _S8',
 'IE410 _S1',
 'IE410 _S2',
 'IE410 _S3',
 'IE410 _S4',
 'IE410 _S5',
 'IE410 _S6',
 'IE410 _S7',
 'IE410 _S8',
 'IE423 _S1',
 'IE423 _S2',
 'IE423 _S3',
 'IE423 _S4',
 'IE423 _S5',
 'IE423 _S6',
 'IE423 _S7',
 'IE423 _S8',
 'IE426 _S1',
 'IE426 _S2',
 'IE426 _S3',
 'IE426 _S4',
 'IE426 _S5',
 'IE426 _S6',
 'IE426 _S7',
 'IE426 _S8',
 'IE427 _S1',
 'IE427 _S2',
 'IE427 _S3',
 'IE427 _S4',
 'IE427 _S5',
 'IE427 _S6',
 'IE427 _S7',
 'IE427 _S8',
 'IE428 _S1',
 'IE428 _S2',
 'IE428 _S3',
 'IE428 _S4',
 'IE428 _S5',
 'IE428 _S6',
 'IE428 _S7',
 'IE428 _S8',
 'IE431 _S1',
 'IE431 _S2',
 'IE431 _S3',
 'IE431 _S4',
 'IE431 _S5',
 'IE431 _S6',
 'IE431 _S7',
 'IE431 _S8',
 'IE435 _S1',
 'IE435 _S2',
 'IE435 _S3',
 'IE435 _S4',
 'IE435 _S5',
 'IE435 _S6',
 'IE435 _S7',
 'IE435 _S8',
 'IE438 _S1',
 'IE438 _S2',
 'IE438 _S3',
 'IE438 _S4',
 'IE438 _S5',
 'IE438 _S6',
 'IE438 _S7',
 'IE438 _S8',
 'IE440 _S1',
 'IE440 _S2',
 'IE440 _S3',
 'IE440 _S4',
 'IE440 _S5',
 'IE440 _S6',
 'IE440 _S7',
 'IE440 _S8',
 'IE503 _S1',
 'IE503 _S2',
 'IE503 _S3',
 'IE503 _S4',
 'IE503 _S5',
 'IE503 _S6',
 'IE503 _S7',
 'IE503 _S8',
 'IE507 _S1',
 'IE507 _S2',
 'IE507 _S3',
 'IE507 _S4',
 'IE507 _S5',
 'IE507 _S6',
 'IE507 _S7',
 'IE507 _S8',
 'IE508 _S1',
 'IE508 _S2',
 'IE508 _S3',
 'IE508 _S4',
 'IE508 _S5',
 'IE508 _S6',
 'IE508 _S7',
 'IE508 _S8',
 'IE517 _S1',
 'IE517 _S2',
 'IE517 _S3',
 'IE517 _S4',
 'IE517 _S5',
 'IE517 _S6',
 'IE517 _S7',
 'IE517 _S8',
 'IE518 _S1',
 'IE518 _S2',
 'IE518 _S3',
 'IE518 _S4',
 'IE518 _S5',
 'IE518 _S6',
 'IE518 _S7',
 'IE518 _S8',
 'IE531 _S1',
 'IE531 _S2',
 'IE531 _S3',
 'IE531 _S4',
 'IE531 _S5',
 'IE531 _S6',
 'IE531 _S7',
 'IE531 _S8',
 'IE533 _S1',
 'IE533 _S2',
 'IE533 _S3',
 'IE533 _S4',
 'IE533 _S5',
 'IE533 _S6',
 'IE533 _S7',
 'IE533 _S8',
 'IE534 _S1',
 'IE534 _S2',
 'IE534 _S3',
 'IE534 _S4',
 'IE534 _S5',
 'IE534 _S6',
 'IE534 _S7',
 'IE534 _S8',
 'IE537 _S1',
 'IE537 _S2',
 'IE537 _S3',
 'IE537 _S4',
 'IE537 _S5',
 'IE537 _S6',
 'IE537 _S7',
 'IE537 _S8',
 'IE538 _S1',
 'IE538 _S2',
 'IE538 _S3',
 'IE538 _S4',
 'IE538 _S5',
 'IE538 _S6',
 'IE538 _S7',
 'IE538 _S8',
 'IE541 _S1',
 'IE541 _S2',
 'IE541 _S3',
 'IE541 _S4',
 'IE541 _S5',
 'IE541 _S6',
 'IE541 _S7',
 'IE541 _S8',
 'IE543 _S1',
 'IE543 _S2',
 'IE543 _S3',
 'IE543 _S4',
 'IE543 _S5',
 'IE543 _S6',
 'IE543 _S7',
 'IE543 _S8',
 'IE562 _S1',
 'IE562 _S2',
 'IE562 _S3',
 'IE562 _S4',
 'IE562 _S5',
 'IE562 _S6',
 'IE562 _S7',
 'IE562 _S8',
 'IE571 _S1',
 'IE571 _S2',
 'IE571 _S3',
 'IE571 _S4',
 'IE571 _S5',
 'IE571 _S6',
 'IE571 _S7',
 'IE571 _S8',
 'IE574 _S1',
 'IE574 _S2',
 'IE574 _S3',
 'IE574 _S4',
 'IE574 _S5',
 'IE574 _S6',
 'IE574 _S7',
 'IE574 _S8',
 'IE579 _S1',
 'IE579 _S2',
 'IE579 _S3',
 'IE579 _S4',
 'IE579 _S5',
 'IE579 _S6',
 'IE579 _S7',
 'IE579 _S8',
 'IE581 _S1',
 'IE581 _S2',
 'IE581 _S3',
 'IE581 _S4',
 'IE581 _S5',
 'IE581 _S6',
 'IE581 _S7',
 'IE581 _S8',
 'IE586 _S1',
 'IE586 _S2',
 'IE586 _S3',
 'IE586 _S4',
 'IE586 _S5',
 'IE586 _S6',
 'IE586 _S7',
 'IE586 _S8',
 'IE590 _S1',
 'IE590 _S2',
 'IE590 _S3',
 'IE590 _S4',
 'IE590 _S5',
 'IE590 _S6',
 'IE590 _S7',
 'IE590 _S8',
 'IE591 _S1',
 'IE591 _S2',
 'IE591 _S3',
 'IE591 _S4',
 'IE591 _S5',
 'IE591 _S6',
 'IE591 _S7',
 'IE591 _S8',
 'IE592 _S1',
 'IE592 _S2',
 'IE592 _S3',
 'IE592 _S4',
 'IE592 _S5',
 'IE592 _S6',
 'IE592 _S7',
 'IE592 _S8',
 'IE599 _S1',
 'IE599 _S2',
 'IE599 _S3',
 'IE599 _S4',
 'IE599 _S5',
 'IE599 _S6',
 'IE599 _S7',
 'IE599 _S8',
 'IE600 _S1',
 'IE600 _S2',
 'IE600 _S3',
 'IE600 _S4',
 'IE600 _S5',
 'IE600 _S6',
 'IE600 _S7',
 'IE600 _S8',
 'IE602 _S1',
 'IE602 _S2',
 'IE602 _S3',
 'IE602 _S4',
 'IE602 _S5',
 'IE602 _S6',
 'IE602 _S7',
 'IE602 _S8',
 'IE605 _S1',
 'IE605 _S2',
 'IE605 _S3',
 'IE605 _S4',
 'IE605 _S5',
 'IE605 _S6',
 'IE605 _S7',
 'IE605 _S8',
 'IE607 _S1',
 'IE607 _S2',
 'IE607 _S3',
 'IE607 _S4',
 'IE607 _S5',
 'IE607 _S6',
 'IE607 _S7',
 'IE607 _S8',
 'IE609 _S1',
 'IE609 _S2',
 'IE609 _S3',
 'IE609 _S4',
 'IE609 _S5',
 'IE609 _S6',
 'IE609 _S7',
 'IE609 _S8',
 'IE610 _S1',
 'IE610 _S2',
 'IE610 _S3',
 'IE610 _S4',
 'IE610 _S5',
 'IE610 _S6',
 'IE610 _S7',
 'IE610 _S8',
 'IE613 _S1',
 'IE613 _S2',
 'IE613 _S3',
 'IE613 _S4',
 'IE613 _S5',
 'IE613 _S6',
 'IE613 _S7',
 'IE613 _S8',
 'IE614 _S1',
 'IE614 _S2',
 'IE614 _S3',
 'IE614 _S4',
 'IE614 _S5',
 'IE614 _S6',
 'IE614 _S7',
 'IE614 _S8',
 'IE615 _S1',
 'IE615 _S2',
 'IE615 _S3',
 'IE615 _S4',
 'IE615 _S5',
 'IE615 _S6',
 'IE615 _S7',
 'IE615 _S8',
 'IE618 _S1',
 'IE618 _S2',
 'IE618 _S3',
 'IE618 _S4',
 'IE618 _S5',
 'IE618 _S6',
 'IE618 _S7',
 'IE618 _S8',
 'IE619 _S1',
 'IE619 _S2',
 'IE619 _S3',
 'IE619 _S4',
 'IE619 _S5',
 'IE619 _S6',
 'IE619 _S7',
 'IE619 _S8',
 'IE622 _S1',
 'IE622 _S2',
 'IE622 _S3',
 'IE622 _S4',
 'IE622 _S5',
 'IE622 _S6',
 'IE622 _S7',
 'IE622 _S8',
 'IE623 _S1',
 'IE623 _S2',
 'IE623 _S3',
 'IE623 _S4',
 'IE623 _S5',
 'IE623 _S6',
 'IE623 _S7',
 'IE623 _S8',
 'IE624 _S1',
 'IE624 _S2',
 'IE624 _S3',
 'IE624 _S4',
 'IE624 _S5',
 'IE624 _S6',
 'IE624 _S7',
 'IE624 _S8',
 'IE625 _S1',
 'IE625 _S2',
 'IE625 _S3',
 'IE625 _S4',
 'IE625 _S5',
 'IE625 _S6',
 'IE625 _S7',
 'IE625 _S8',
 'IE626 _S1',
 'IE626 _S2',
 'IE626 _S3',
 'IE626 _S4',
 'IE626 _S5',
 'IE626 _S6',
 'IE626 _S7',
 'IE626 _S8',
 'IE627 _S1',
 'IE627 _S2',
 'IE627 _S3',
 'IE627 _S4',
 'IE627 _S5',
 'IE627 _S6',
 'IE627 _S7',
 'IE627 _S8',
 'IE628 _S1',
 'IE628 _S2',
 'IE628 _S3',
 'IE628 _S4',
 'IE628 _S5',
 'IE628 _S6',
 'IE628 _S7',
 'IE628 _S8',
 'IE629 _S1',
 'IE629 _S2',
 'IE629 _S3',
 'IE629 _S4',
 'IE629 _S5',
 'IE629 _S6',
 'IE629 _S7',
 'IE629 _S8',
 'IE630 _S1',
 'IE630 _S2',
 'IE630 _S3',
 'IE630 _S4',
 'IE630 _S5',
 'IE630 _S6',
 'IE630 _S7',
 'IE630 _S8',
 'IE631 _S1',
 'IE631 _S2',
 'IE631 _S3',
 'IE631 _S4',
 'IE631 _S5',
 'IE631 _S6',
 'IE631 _S7',
 'IE631 _S8',
 'IE632 _S1',
 'IE632 _S2',
 'IE632 _S3',
 'IE632 _S4',
 'IE632 _S5',
 'IE632 _S6',
 'IE632 _S7',
 'IE632 _S8',
 'IE999 _S1',
 'IE999 _S2',
 'IE999 _S3',
 'IE999 _S4',
 'IE999 _S5',
 'IE999 _S6',
 'IE999 _S7',
 'IE999 _S8']

In [20]:
length = len(all_list)
length

912

In [21]:
if len(all_list) == X.shape[1]:
    # Assign the new column names
    X.columns = all_list
else:
    print(f"Error: The number of new column names ({len(all_list)}) does not match the number of columns ({X.shape[1]})")

In [22]:
X

,Admission_line,Entrance year,Entrance grade,Graduation year,Graduation semester,Gender,Graduation status,Graduation grade,IE101 _S1,IE101 _S2,...,IE632 _S7,IE632 _S8,IE999 _S1,IE999 _S2,IE999 _S3,IE999 _S4,IE999 _S5,IE999 _S6,IE999 _S7,IE999 _S8
0,3,0,0,0,0,2,0,0,69,0,...,0,0,0,0,0,0,0,0,0,0
1,4,0,0,0,0,2,0,0,90,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0,0,0,0,1,0,0,75,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,0,0,1,0,0,74,0,...,0,0,0,0,0,0,0,0,0,0
4,5,0,0,0,0,2,0,0,60,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,3,0,0,0,0,2,0,0,69,0,...,0,0,0,0,0,0,0,0,0,0
730,3,0,0,0,0,2,0,0,82,0,...,0,91,0,0,0,0,0,0,0,0
731,3,0,0,0,0,2,0,0,61,0,...,0,0,0,0,0,0,0,0,0,0
732,3,0,0,0,0,2,0,0,45,0,...,0,0,0,0,0,0,0,0,0,0
733,4,0,0,0,0,2,0,0,76,0,...,0,0,0,0,0,0,0,0,0,90

# Remove zero column

In [23]:
# (X != 0).any(axis=0) --> this locate columns which has all zero value within them
# X.loc[:,(X != 0).any(axis=0)] --> this remove the columns that have all zero values 
NonZero = (X != 0).any(axis=0)
X = X.loc[:, NonZero]

In [24]:
X

,Admission_line,Gender,IE101 _S1,IE101 _S2,IE101 _S3,IE101 _S4,IE101 _S5,IE101 _S6,IE101 _S7,IE109 _S1,...,IE625 _S7,IE626 _S6,IE626 _S8,IE628 _S8,IE629 _S7,IE630 _S8,IE631 _S8,IE632 _S8,IE999 _S6,IE999 _S8
0,3,2,69,0,0,0,0,0,0,64,...,0,0,0,0,0,0,0,0,0,0
1,4,2,90,0,0,0,0,0,0,95,...,0,0,0,0,0,0,0,0,0,0
2,3,1,75,0,0,0,0,0,0,89,...,0,0,0,0,0,0,0,0,0,0
3,3,1,74,0,0,0,0,0,0,57,...,0,0,0,0,0,0,0,0,0,0
4,5,2,60,0,0,0,0,0,0,77,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,3,2,69,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
730,3,2,82,0,0,0,0,0,0,97,...,0,0,0,0,0,0,0,91,0,0
731,3,2,61,0,0,0,0,0,0,66,...,0,0,0,0,0,0,0,0,0,0
732,3,2,45,0,0,0,82,0,0,65,...,0,0,0,0,0,0,0,0,0,0
733,4,2,76,0,0,0,0,0,0,76,...,0,0,0,0,0,0,86,0,0,90

In [25]:
y

1      0
2      0
3      1
4      1
5      0
      ..
730    0
731    0
732    0
733    0
734    0
Name: Unnamed: 16, Length: 734, dtype: object

In [26]:
# Concatenate y to x 
# since there is NaN in the y data, we need to reset the indices of y
y = y.reset_index(drop=True)
Data = pd.concat([X,y],axis = 1)
Data

,Admission_line,Gender,IE101 _S1,IE101 _S2,IE101 _S3,IE101 _S4,IE101 _S5,IE101 _S6,IE101 _S7,IE109 _S1,...,IE626 _S6,IE626 _S8,IE628 _S8,IE629 _S7,IE630 _S8,IE631 _S8,IE632 _S8,IE999 _S6,IE999 _S8,Unnamed: 16
0,3,2,69,0,0,0,0,0,0,64,...,0,0,0,0,0,0,0,0,0,0
1,4,2,90,0,0,0,0,0,0,95,...,0,0,0,0,0,0,0,0,0,0
2,3,1,75,0,0,0,0,0,0,89,...,0,0,0,0,0,0,0,0,0,1
3,3,1,74,0,0,0,0,0,0,57,...,0,0,0,0,0,0,0,0,0,1
4,5,2,60,0,0,0,0,0,0,77,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,3,2,69,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
730,3,2,82,0,0,0,0,0,0,97,...,0,0,0,0,0,0,91,0,0,0
731,3,2,61,0,0,0,0,0,0,66,...,0,0,0,0,0,0,0,0,0,0
732,3,2,45,0,0,0,82,0,0,65,...,0,0,0,0,0,0,0,0,0,0
733,4,2,76,0,0,0,0,0,0,76,...,0,0,0,0,0,86,0,0,90,0

In [27]:
#excel_file_path = 'D:\\AI Warning\\3_CNN\\Data and Classification Model\\Classification\\Trial data\\Classification S8.xlsx'
#Data.to_excel(excel_file_path, index=False)

In [28]:

excel_file_path = 'D:\\AI Warning\\3_CNN\\Data and Classification Model\\Matching 108\\102-108\\Classification_combined_index.xlsx'

# Your DataFrame (assuming it's called Data)
with pd.ExcelWriter(excel_file_path, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
    Data.to_excel(writer, sheet_name="S8", index=False)
#if_sheet_exists='replace' or 'new'